### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by scriptdad** [lynxbinz/CS-Beacon-Notifier#1]
When I execute the test 'python3 pyScript.py 123', telegram can receive notifications. But the script does not send notifications, my version is 4.7

**Comment by lynxbinz** [comment]
I have tested the script and it working just fine. Make sure you follow my step in the description or you need to reset your CB if the issue still exist.

**Comment by lynxbinz** [comment]
Since have no reply, so i have to close this issue.
